version: '3'

services:
  mysql:
    image: 'mysql:latest'
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "--silent" ]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      - 'MYSQL_ROOT_PASSWORD=s3cr3t'
      - 'MYSQL_USER=arithmetics'
      - 'MYSQL_DATABASE=arithmetics'
      - 'MYSQL_PASSWORD=s3cr3t'
 
  arithmetics:
    image: public.ecr.aws/j3c6d5f6/arithmetics:latest ## Uncomment this to pull from AWS ECR and comment out build
    #build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - 'JDBC_URL=mysql:3306/arithmetics'
      - 'JDBC_USER=arithmetics'
      - 'JDBC_PASSWORD=s3cr3t'

  arithmetics-ui:
    #build: .
    image: public.ecr.aws/j3c6d5f6/arithmetics-ui:latest
    depends_on:
      - 'arithmetics'
    ports:
      - '80:80'